//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoGrupo_1.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCarrito
    {
        public int idCarrito { get; set; }
        public int id { get; set; }
        public int idProducto { get; set; }
        public int Cantidades { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual tProducto tProducto { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
