//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoGrupo_1.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCarrito
    {
        public int idCarrito { get; set; }
        public int id { get; set; }
        public int idProducto { get; set; }
        public int Cantidades { get; set; }
        public System.DateTime Fecha { get; set; }
    
        public virtual tProducto tProducto { get; set; }
        public virtual tUsuario tUsuario { get; set; }
    }
}
