//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace proyectoGrupo_1.BaseDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class tSeguimiento
    {
        public int idUsuario { get; set; }
        public int idSeguimiento { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> fechaIngreso { get; set; }
        public Nullable<System.DateTime> fechaSalida { get; set; }
    
        public virtual tUsuario tUsuario { get; set; }
    }
}
